### ISSUE TITLE
Usage link not found

### ISSUE THREAD

**Issue by datsuns** [kazuhito-m/mindmeister2trello-importer#3]
a link of Usage information in [README.md](https://github.com/kazuhito-m/mindmeister2trello-importer/blob/master/README.md) links to http://kazuhito-m.github.io/tech/2015/11/01/

but that url is not active... (README.js.md also)
plz update to correct url !

**Comment by datsuns** [comment]
i found youre blog post from that link !!  thx a lot !!

**Comment by kazuhito-m** [comment]
Thank you very much, same here.
